-- jdbc:postgresql://localhost:5432/university_db

-- CREATE TABLE students
-- (
--     Id SERIAL PRIMARY KEY,
--     FirstName CHARACTER VARYING(30),
--     LastName CHARACTER VARYING(30),
--     Email CHARACTER VARYING(30),
--     Age INTEGER
-- )
-- INSERT INTO students (id, firstname, lastname, email, age) VALUES (DEFAULT, 'Eugene', 'Last', 'Eugene', 29)